list_of_signoffs = \
    ['At rock bottom,',
     'In the trenches, but it might be the latrine,',
     'All blues, zero clues,',
     'Same panic, different disco,',
     'Dead inside,',
     'P Sherman, 42 Wallaby Way, Sydney,',
     'Just keep swimming,',
     'Screaming internally,',
     'Screaming into the void,',
     'Surviving, but not even close to thriving,',
     'On the edge,',
     'I hope this email finds you before I do,',
     "I hope this email doesn't find you, I hope you made it out,",
     'Hanging by a thread,',
     'Have the day you deserve,',
     'Step on a Lego,',
     'May your day be as pleasant as you are,',
     "You'll never take me alive,",
     'Signing off from the abyss,',
     'May the crows guide you,',
     'Beep boop,',
     'This is fine,',
     'This is fine, everything is fine,',
     "I'm just going to put this over here, with the rest of the... fire,",
     'Plotting my escape from the simulation,',
     'Fueled by existential dread and caffeine,',
     'Off to wrangle some squirrels,',
     "I'm not a robot, I swear,",
     'Not responsible for any spontaneous combustion this email may cause,',
     '(in the voice of Chandler Bing) Could I BE any more dead inside?,',
     '(in the voice of Dora the Explorer) Can you say "existential crisis"?,',
     "Don't be a part of the problem. Be the entire problem,",
     'Live, Laugh, Toaster Bath,',]

if __name__ == '__main__':
 None